### ISSUE TITLE
Major feature roadmap

### ISSUE THREAD

**Issue by sveinugu** [fairtracks/omnipy#215]
Or more of an unorganised wishlist for now:

- [ ] Move to pydantic v2
- [x] Support Python 3.14
- [ ] Merge all half-finished branches
- [ ] Return data/logs from prefect/kubernetes
- [ ] Streamlined running of jobs on prefect/kubernetes
- [x] Full support for async/parallel runs
- [x] Omnified async http requests w/rate limits
- [x] Refactor Dataset load() as async retrieval
- [ ] Improved interactive data view w/tables/scrolling etc (external library)
- [ ] Automatic snapshot for job runs
- [ ] Refactor to more explicitly support conversions
- [ ] Refactor serializers
- [ ] Refactor job modifiers to be included only if parameters are set 
- [ ] Integration with Whyqd
- [x] Support for Models of Datasets
- [ ] Refactor MultiModelDataset to Dataset[PydanticModel]
- [ ] Documentation
- [ ] Integration with BioNumpy and Numpy
- [ ] Integration with Excel
- [ ] XML support
- [ ] YAML support
- [ ] JSON-LD support
- [ ] Auto-Normalisation of relational tables
- [ ] Relational tables -> Hierarchical JSON
- [ ] Auto-mapping from relational tables to single table
- [ ] Tests and documentation of all included tasks and flows
- [ ] Uniform indexing across JSON, Pandas, Numpy, etc
- [ ] Improved table conversions
- [ ] Automatic schema detection
- [ ] Integration with LinkML
- [x] Improved job parameters (see skipped tests in https://github.com/dhis2/chap-core/blob/master/tests/data_wrangling/test_standardize_data.py)
